sudo: required
language: generic


install:
  - sudo apt-get install nodejs npm
  - npm config set strict-ssl false
  - sudo npm i html-validator-cli -g

script:
  - html-validator --file=index.html --verbose


notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    recipients:
      - southparkfan@miraheze.org
      - macfan@miraheze.org
    on_success: change
    on_failure: always
